### ISSUE TITLE
Exposable?

### ISSUE THREAD

**Issue by MysticRyuujin** [dappnode/DAppNodePackage-rotki#19]
Just putting it here for comment / input - do you thing Rotki should be exposable?

It's a web app, so it can be, but the question is does it fall under the category of "safe to expose" where we could include it as an option?

```json
"exposable": [
    {
      "name": "Rotki",
      "description": "Rotki Webapp",
      "serviceName": "rotki.dnp.dappnode.eth",
      "port": 80
    }
  ]
```

**Comment by tropicar** [comment]
Currently, we are not adding UI apps as exposable because it can be unsafe and people who are not technical maybe they are not concerned about the risk they are taking if they expose some packages. Anyway, an user can do it manually. Going to the package, network, https part and set IP the port.
