### ISSUE TITLE
Make it easier for users to enable the debug log level

### ISSUE THREAD

**Issue by kelsos** [dappnode/DAppNodePackage-rotki#29]
**Is your feature request related to a problem? Please describe.**

We want to make it easier for us to help the DAppNode package users provide us with debug logs when a problem occurs. By default, the docker image runs in `critical` mode which means that it does not log anything. 

At the moment there is no easy way for the users to turn the `debug` logging level on when running the DAppNode package. 

The logs are stored by default to the log volume (`/logs`).

**Describe the solution you'd like**

A dropdown/menu option in DAppNode where a user can change the rotki log level would be really useful.

**Describe alternatives you've considered**

--

**Additional context**

The docker image accepts the log level as the environment variable `LOGLEVEL` or as part of a configuration file that is mounted to a volume (`/config`). The config file's name is `rotki_config.json` and the loglevel should be specified in the following format.

```json
{
  "loglevel": "debug"
}
```

rotki supports the following levels:

- critical
- error
- warning
- info
- debug
- trace

**Comment by tropicar** [comment]
I have created this PR where we added an environment var called LOGLEVEL  and the user can change it from the UI but i dont see so much difference in the logs after changing the value, i see for example the API calls with error as a value of the loglevel var for example:
```
172.33.8.2 - - [02/Nov/2022:16:38:00 +0000] "GET /api/1/info?check_for_updates=false HTTP/1.1" 200 160 "http://rotki.dappnode/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
172.33.8.2 - - [02/Nov/2022:16:38:01 +0000] "GET /api/1/info?check_for_updates=true HTTP/1.1" 200 165 "http://rotki.dappnode/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [02/Nov/2022:16:38:13 +0000] "GET /api/1/ping HTTP/1.1" 200 31 "-" "curl/7.74.0" "-"
``` 
Can you test it or tell me a way how to check it? Maye i am checking it in a wrong way

**Comment by kelsos** [comment]
@tropicar the container needs to be restarted for the log level to apply.

**Comment by tropicar** [comment]
> @tropicar the container needs to be restarted for the log level to apply.

After changing a value of a env var in the UI the container that uses that UI is restarted automatically, but even after restarting the container manually after set up the env var, i dotn see different logs.

**Comment by kelsos** [comment]
> > @tropicar the container needs to be restarted for the log level to apply.
> 
> After changing a value of an env var in the UI the container that uses that UI is restarted automatically, but even after restarting the container manually after setting up the env var, i don't see different logs.

Ok I think I know why, these are the Nginx logs we are seeing here, the backend logs should be in the `/logs` volume as a file. They are not pushed to standard output so they should not be visible.

**Comment by LefterisJP** [comment]
We need a solution here @kelsos and @tropicar. Dappnode + rotki users are increasing and we are unable to help since there is no way to get logs. We end up telling them to install the desktop app. This should not have to happen.

**Comment by mgarciate** [comment]
@LefterisJP @kelsos let me take a look at the `loglevel` environment variable. Ask the user to navigate to the File Manager tab of the package and download the `logs/rotki.log` is a valid solution for you? (through the Dappnode UI 👇)

<img width="1287" alt="image" src="https://github.com/dappnode/DAppNodePackage-rotki/assets/7695193/d7dd57b3-3165-4a6b-95ae-458a10b5bb7b">

@kelsos mentioned and he's right that the container logs shows the nginx logs instead of rotki's

**Comment by kelsos** [comment]
Yes asking the user to navigate to the file manager tab and download the file from there is a valid solution. If you can with the log level setting that would really be appreciated.

**Comment by mgarciate** [comment]
> Yes asking the user to navigate to the file manager tab and download the file from there is a valid solution. If you can with the log level setting that would really be appreciated.

Alright. Will be available within the next release. The user will be able to change de log level via dropdown control
