### ISSUE TITLE
Documentation about getting started

### ISSUE THREAD

**Issue by yabirgb** [dappnode/DAppNodePackage-rotki#34]
The getting started documentation (https://github.com/dappnode/DAppNodePackage-rotki/blob/main/getting-started.md) contains outdated instructions for how to setup the ethereum nodes. We think it would be better to link to our docs there https://rotki.readthedocs.io/en/latest/usage_guide.html#rpc-nodes and then provide the information for the different nodes

Thanks for taking care of the dappnode package :)

**Comment by tropicar** [comment]
I have updated the content of the getting started the section with the next text:
`## Welcome to your Rotki app: The portfolio manager that protects your privacy

Now you can:

- Visit your Rotki **dashboard**: **[rotki.dappnode](http://rotki.dappnode/)**.
- Rotki must have access to a synchronized Ethereum node. You will need to have installed an Execution client and Consensus client(Prysm, Teku, Lighthouse or Nimbus) You can do that from System > Repository or directly from the stakers-ui.

You can find in the Rotki documentation the information on the different nodes you can use [Rotki](https://rotki.readthedocs.io/en/latest/usage_guide.html#rpc-nodes)

- Explore the [Rotki documentation](https://rotki.readthedocs.io/en/latest/usage_guide.html) for more information about what can you do with Rotki.
`

**Comment by tropicar** [comment]
it will be added in the next release, if you think we should add more information , i will add it .
