### ISSUE TITLE
Can't login to Rotki on Dappnode. 502 for API ping

### ISSUE THREAD

**Issue by Beasta** [dappnode/DAppNodePackage-rotki#63]
**Describe the bug**
502 error on the api ping. App won't login on dappnode. See screenshot.

I've tried uninstalling and reinstalling to no success. I've also tried on multiple browsers.

**To Reproduce**

1. Install Version: 0.1.30 (v1.33.1 upstream)
2. Try to open the app
3. 
**Expected behavior**

Should be able to login

**Screenshots**
![Screenshot 2024-06-24 at 10 36 38 AM](https://github.com/dappnode/DAppNodePackage-rotki/assets/6305836/484fa897-7de0-42ea-9b4b-4ec854f13ee4)

![Screenshot 2024-06-24 at 10 43 29 AM](https://github.com/dappnode/DAppNodePackage-rotki/assets/6305836/a3fa9927-a9f4-42d9-93ac-a1e0801e7e0f)

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.11
core.dnp.dappnode.eth: 0.2.94
dappmanager.dnp.dappnode.eth: 0.2.88, commit: bf8d074b
https.dnp.dappnode.eth: 0.2.1
ipfs.dnp.dappnode.eth: 0.2.23
vpn.dnp.dappnode.eth:
wifi.dnp.dappnode.eth: 0.2.9
wireguard.dnp.dappnode.eth: 0.1.3
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.6
dockerCliVersion: 20.10.6
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-18-amd64
Disk usage: 88%

- Package version: 
- OS: 
- Browser

**Comment by mgarciate** [comment]
> **Describe the bug** 502 error on the api ping. App won't login on dappnode. See screenshot.
> 
> I've tried uninstalling and reinstalling to no success. I've also tried on multiple browsers.
> 
> **To Reproduce**
> 
> 1. Install Version: 0.1.30 (v1.33.1 upstream)
> 2. Try to open the app
> 
> **Expected behavior**
> 
> Should be able to login
> 
> **Screenshots** ![Screenshot 2024-06-24 at 10 36 38 AM](https://private-user-images.githubusercontent.com/6305836/342438919-484fa897-7de0-42ea-9b4b-4ec854f13ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTI2NTYsIm5iZiI6MTcxOTI1MjM1NiwicGF0aCI6Ii82MzA1ODM2LzM0MjQzODkxOS00ODRmYTg5Ny03ZGUwLTQyZWEtOWI0Yi00ZWM4NTRmMTNlZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTgwNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdmZWE3MTIzNTM3Zjk2NWZmMWNlNzM1YmVkMWIyZjU2Nzk5ZWI3MzNjMjEyNjM4ODhjNjI5ZjIxYmVmZjlkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QweUfCuxFTh9XTu4E9b0IZXnvndflVOXnQGejclZ5Ic)
> 
> ![Screenshot 2024-06-24 at 10 43 29 AM](https://private-user-images.githubusercontent.com/6305836/342439858-a3fa9927-a9f4-42d9-93ac-a1e0801e7e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTI2NTYsIm5iZiI6MTcxOTI1MjM1NiwicGF0aCI6Ii82MzA1ODM2LzM0MjQzOTg1OC1hM2ZhOTkyNy1hOWY0LTQyZDktOTNhYy1hMWUwODAxZTdlMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTgwNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmEzYTBlNjgyMzUxMjFiYmFhZDg2ZmE2NDQ0OGY1MTc2ZTU3NjE2ZWIxNzkyN2M0N2UwMmEyZDIyYTNlMjAzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jPchO4BpwAUQFlJiosGRaCYjQcH676stF_kxZL2Zdcc)
> 
> **DAppNode version:**
> 
> Core DAppNode Packages versions bind.dnp.dappnode.eth: 0.2.11 core.dnp.dappnode.eth: 0.2.94 dappmanager.dnp.dappnode.eth: 0.2.88, commit: bf8d074b https.dnp.dappnode.eth: 0.2.1 ipfs.dnp.dappnode.eth: 0.2.23 vpn.dnp.dappnode.eth: wifi.dnp.dappnode.eth: 0.2.9 wireguard.dnp.dappnode.eth: 0.1.3 System info dockerComposeVersion: 1.25.5 dockerServerVersion: 20.10.6 dockerCliVersion: 20.10.6 os: debian versionCodename: bullseye architecture: amd64 kernel: 5.10.0-18-amd64 Disk usage: 88%
> 
> * Package version:
> * OS:
> * Browser

@Beasta please, you should update Docker via http://my.dappnode/system/advanced
Check those messages https://discord.com/channels/747647430450741309/747816600077598730/1242428787266687057

**Comment by jimjimvalkema** [comment]
> > **Describe the bug** 502 error on the api ping. App won't login on dappnode. See screenshot.
> > I've tried uninstalling and reinstalling to no success. I've also tried on multiple browsers.
> > **To Reproduce**
> > 
> > 1. Install Version: 0.1.30 (v1.33.1 upstream)
> > 2. Try to open the app
> > 
> > **Expected behavior**
> > Should be able to login
> > **Screenshots** ![Screenshot 2024-06-24 at 10 36 38 AM](https://private-user-images.githubusercontent.com/6305836/342438919-484fa897-7de0-42ea-9b4b-4ec854f13ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTI2NTYsIm5iZiI6MTcxOTI1MjM1NiwicGF0aCI6Ii82MzA1ODM2LzM0MjQzODkxOS00ODRmYTg5Ny03ZGUwLTQyZWEtOWI0Yi00ZWM4NTRmMTNlZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTgwNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdmZWE3MTIzNTM3Zjk2NWZmMWNlNzM1YmVkMWIyZjU2Nzk5ZWI3MzNjMjEyNjM4ODhjNjI5ZjIxYmVmZjlkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QweUfCuxFTh9XTu4E9b0IZXnvndflVOXnQGejclZ5Ic)
> > ![Screenshot 2024-06-24 at 10 43 29 AM](https://private-user-images.githubusercontent.com/6305836/342439858-a3fa9927-a9f4-42d9-93ac-a1e0801e7e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTI2NTYsIm5iZiI6MTcxOTI1MjM1NiwicGF0aCI6Ii82MzA1ODM2LzM0MjQzOTg1OC1hM2ZhOTkyNy1hOWY0LTQyZDktOTNhYy1hMWUwODAxZTdlMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTgwNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmEzYTBlNjgyMzUxMjFiYmFhZDg2ZmE2NDQ0OGY1MTc2ZTU3NjE2ZWIxNzkyN2M0N2UwMmEyZDIyYTNlMjAzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jPchO4BpwAUQFlJiosGRaCYjQcH676stF_kxZL2Zdcc)
> > **DAppNode version:**
> > Core DAppNode Packages versions bind.dnp.dappnode.eth: 0.2.11 core.dnp.dappnode.eth: 0.2.94 dappmanager.dnp.dappnode.eth: 0.2.88, commit: bf8d074b https.dnp.dappnode.eth: 0.2.1 ipfs.dnp.dappnode.eth: 0.2.23 vpn.dnp.dappnode.eth: wifi.dnp.dappnode.eth: 0.2.9 wireguard.dnp.dappnode.eth: 0.1.3 System info dockerComposeVersion: 1.25.5 dockerServerVersion: 20.10.6 dockerCliVersion: 20.10.6 os: debian versionCodename: bullseye architecture: amd64 kernel: 5.10.0-18-amd64 Disk usage: 88%
> > 
> > * Package version:
> > * OS:
> > * Browser
> 
> @Beasta please, you should update Docker via http://my.dappnode/system/advanced Check those messages https://discord.com/channels/747647430450741309/747816600077598730/1242428787266687057

i had to install docker with `sudo apt-get install docker` after that it worked!
